# Generated by Django 3.0.8 on 2020-07-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(help_text='An image that demonstrates the working project', upload_to=''),
        ),
    ]
