# Generated by Django 3.1.7 on 2021-02-23 14:01

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('small_body', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('slug', models.SlugField(blank='True', null='True')),
            ],
            options={
                'verbose_name': 'Anexa',
                'verbose_name_plural': 'Anexe',
                'ordering': ['-created', '-name'],
            },
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('main_body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('small_body', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('slug', models.SlugField(blank='True', null='True')),
                ('anexe', models.ManyToManyField(to='api.Anexa')),
            ],
            options={
                'verbose_name': 'Produs',
                'verbose_name_plural': 'Produse',
                'ordering': ['-created', '-name'],
            },
        ),
        migrations.CreateModel(
            name='ImaginiProdus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.produs')),
            ],
            options={
                'verbose_name': 'Imagine Produs',
                'verbose_name_plural': 'Imagini Produs',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ImaginiAnexa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('anexa', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.anexa')),
            ],
            options={
                'verbose_name': 'Imagine Produs',
                'verbose_name_plural': 'Imagini Produs',
                'ordering': ['-created'],
            },
        ),
    ]
