# Generated by Django 3.1.2 on 2021-04-27 07:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imaginianexe_imaginiproduse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imaginianexe',
            options={'ordering': ['-created'], 'verbose_name': 'Imagini anexa', 'verbose_name_plural': 'Imagini anexe'},
        ),
        migrations.RenameField(
            model_name='anexa',
            old_name='main_body',
            new_name='descriere',
        ),
        migrations.RenameField(
            model_name='produs',
            old_name='main_body',
            new_name='descriere',
        ),
        migrations.AddField(
            model_name='anexa',
            name='detalii',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anexa',
            name='specificatii',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produs',
            name='detalii',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produs',
            name='specificatii',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
